### ISSUE TITLE
->optimize() cannot be call multiple times

### ISSUE THREAD

**Issue by cjobeili** [wp-media/imagify-php#5]
Hi, 

You have a bug in your library. You cannot call multiple times the ->optimise() method with the same instance of Imagify.

Here is the reproduction:

file test.php
```
<?php
namespace Imagify;

class Toto
{
        public function test(){

                if ( !function_exists('curl_file_create') ) {
                        echo ".";
            function curl_file_create($filename, $mimetype = '', $postname = '') {
                return "@$filename;filename=" . ( $postname ?: basename($filename) ) . ( $mimetype ? ";type=$mimetype" : '' );
            }
        }
        }
}
```
file test2.php
```
<?php
require __DIR__.'/test.php';

use Imagify\Toto;
$p  = new Toto();
$p->test();
$p->test();
```

Result:

Fatal error: Cannot redeclare Imagify\curl_file_create() (previously declared in /Users/clement/test.php:11) in /Users/clement/test.php on line 11

The solution is to not create function inside of a method.

**Comment by Shakup** [comment]
@cjobeili thanks :)
